"""edit products column user_id to seller_id

Revision ID: 33b95eef2be6
Revises: 73f8eb14a339
Create Date: 2024-04-18 11:26:13.022312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33b95eef2be6'
down_revision: Union[str, None] = '73f8eb14a339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('seller_id', sa.Integer(), nullable=False))
    op.drop_constraint('products_user_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'sellers', ['seller_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('products', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_user_id_fkey', 'products', 'sellers', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('products', 'seller_id')
    # ### end Alembic commands ###
