"""rename verification_id to verification_url

Revision ID: 4148ea23236c
Revises: 85d8bdd79096
Create Date: 2024-04-13 11:19:13.110647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4148ea23236c'
down_revision: Union[str, None] = '85d8bdd79096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('verification_url', sa.String(), nullable=True))
    op.drop_column('sellers', 'verification_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('verification_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('sellers', 'verification_url')
    # ### end Alembic commands ###
