"""add shipping_fee column on products

Revision ID: 467fa151df50
Revises: 14523852c6f2
Create Date: 2024-05-03 23:13:22.650822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '467fa151df50'
down_revision: Union[str, None] = '14523852c6f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('shipping_fee', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'shipping_fee')
    # ### end Alembic commands ###
