"""add order_size column in order_items

Revision ID: 7f3fa3eb6061
Revises: 7b3e9cb729c0
Create Date: 2024-04-30 13:54:36.861561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f3fa3eb6061'
down_revision: Union[str, None] = '7b3e9cb729c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('order_size', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_items', 'order_size')
    # ### end Alembic commands ###
