"""add user_id column in sellers table

Revision ID: 85d8bdd79096
Revises: 823096149411
Create Date: 2024-04-13 11:15:25.024194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85d8bdd79096'
down_revision: Union[str, None] = '823096149411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sellers', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sellers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sellers', type_='foreignkey')
    op.drop_column('sellers', 'user_id')
    # ### end Alembic commands ###
