"""add unit and rating column products

Revision ID: e3a3043afacf
Revises: e93f8f284633
Create Date: 2024-04-18 13:16:12.539041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3a3043afacf'
down_revision: Union[str, None] = 'e93f8f284633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('rating', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'rating')
    # ### end Alembic commands ###
